### ISSUE TITLE
Unhandled rejection TypeError: client.end is not a function

### ISSUE THREAD

**Issue by mccrodp** [shoov/shoov#368]
Making some good progress:

* Have default homepage test running locally
* Deployed same image to Digital Ocean: https://hub.docker.com/r/mccrodp/shoov/
* Ran container using: `sudo docker run -i -t mccrodp/shoov /bin/bash`
* Copied in my `.shoov.json` file to `/home/shoov`
* Ran installer successfully: `yo shoov --base-url=https://my-url.com`
* **Errors then with running the command in visual monitor dir below**

````shell
cd visual-monitor/
shoov@ccd40bd14df5:~/visual-monitor$ PROVIDER_PREFIX=saucelabs SELECTED_CAPS=chrome mocha


  Visual monitor testing
    1) "before all" hook
Unhandled rejection TypeError: client.end is not a function
    at /home/shoov/visual-monitor/node_modules/shoov-webdrivercss/index.js:236:16
    at tryCatcher (/home/shoov/visual-monitor/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
````

**Comment by mccrodp** [comment]
I thought this may have been to do with my Saucelabs trial that had expired, but I just bought a monthly plan now: $29 / month Manual plan. Is this plan sufficient, or do you need something more specific? Thank you!

**Comment by amitaibu** [comment]
Is running same test against shoov's default backend working?

**Comment by mccrodp** [comment]
Hey @amitaibu, thanks for the suggestion.

I created a new container and went through the process again, this time against what I believe is Shoov's default backend: `yo shoov --base-url=https://app.shoov.io`

```
cd visual-monitor/
shoov@38536e8a7f9b:~/visual-monitor$ PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha


  Visual monitor testing
    1) "before all" hook
Unhandled rejection TypeError: client.end is not a function
    at /home/shoov/visual-monitor/node_modules/shoov-webdrivercss/index.js:236:16
    at tryCatcher (/home/shoov/visual-monitor/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

I wonder can this come from some kind of cloud based docker or network issue. I have been able to successfully ping out and run `curl -sS shoov.io` though, so not sure.

**Comment by mccrodp** [comment]
I also tried locally using docker `docker run -i -t mccrodp/shoov /bin/bash` with the above image with the same issue. Interesting, if you just use the Dockerfile directly to build the image, rather than the image on Docker Hub, then it works. https://github.com/mccrodp/shoov.git

It did look a little different though when doing the composer install to what I saw on Digital Ocean:

```
Composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)stall loadCurrentTree
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
Failed to decode response: zlib_decode(): data errorstry uri https://registry.npmjs.org/cross-spawn
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
```

It fails to download directly and compiles from source, this is what I saw also when it worked manually building, so it should be ok.

```
Failed to download symfony/event-dispatcher from dist: The zip extension and unzip command are both missing, skipping.
A php.ini file does not exist. You will have to create one.
    Now trying to download from source
  - Installing symfony/event-dispatcher (v2.8.13)
    Cloning 25c576abd4e0f212e678fe8b2bd9a9a98c7ea934
```

I'll have to take a look at this one closer, the image built successfully on Docker Hub, so should be the same, just not sure if this is a dependency related issue, or something network related, etc.

**Comment by amitaibu** [comment]
what's in your `~/.shoov.json`?

**Comment by mccrodp** [comment]
This `~/.shoov.json` previously worked on the custom build of https://github.com/mccrodp/shoov.git, just doesn't seem to on https://hub.docker.com/r/mccrodp/shoov/

``` json
{"access_token":"-------","browserstack_username":null,"browserstack_key":null,"sauce_username":"-----","sauce_access_key":"---------"
```

**Comment by mccrodp** [comment]
My latest error when trying a local build is shown below.

I'm not sure if this is due to adding the `~/.shoov.json` after initially running the `yo shoov` installer, but I re-ran it after and still got the below.

````shell
PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha


  Visual monitor testing
    1) "before all" hook
Unhandled rejection Error: Command failed: git config --get remote.origin.url

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
Unhandled rejection Error: Command failed: git rev-parse --show-prefix
fatal: Not a git repository (or any of the parent directories): .git
````

**Comment by amitaibu** [comment]
No, the error is there:

> fatal: Not a git repository (or any of the parent directories): .git

So its either not a git repo, or you don't have any commit logs.

**Comment by mccrodp** [comment]
>So its either not a git repo, or you don't have any commit logs.

Thanks @amitaibu, but I'm a little slow here as I haven't come across this one before (when I had this working). 

What specifically isn't a git repo? I ran `yo shoov --base-url=https://app.shoov.io` which seemed to run successfully. Does whatever is in `/home/shoov` require a .git folder / be initialised as a repository? If so, why is this?

**Comment by amitaibu** [comment]
To confirm: 

Is the dir you run this test in a github repo?
If so, when you do `git log` - are there several commits?

**Comment by mccrodp** [comment]
Ahh, I get it now, thanks, as in http://shoov.io/tutorials/lesson2-scaffold/ - "Lesson 2 - Setup a GitHub repository"

This is interesting then and makes sense why there maybe this issue. I had the Github repo: https://github.com/mccrodp/shoov

It was working when using this, but since I have setup the build pointing to this repo from Docker Cloud it must build the files in the repo but not include the repo files / .git folder itself.

I'll have to look into this one, but I guess it makes sense why Docker Cloud doesn't include these. I don't know enough about Shoov yet as to why it needs the repo files and perhaps I need to go through the docs again if it says there 😝

**Comment by mccrodp** [comment]
````
shoov@ad37c9d9bde1:~$ grep -rn "git rev-parse --show-prefix" .
./visual-monitor/node_modules/shoov-webdrivercss/index.js:56:  exec('git rev-parse --show-prefix', function(err, stdout) {
````

I see it's in the nodejs package. Is there anyway to bypass this or use an alternate method? At the moment it looks like a deal breaker for implementing a Docker deployed approach to running shoov tests, unless I'm missing something of course.

**Comment by amitaibu** [comment]
why deal breaker? It's just checks you are running inside a git project.

You might be able to code around it, to not be coupled with a Git(Hub) repo, but that's a use case I haven't catered for.

As a work around you can always git init, git commit  - and discard it later.

**Comment by mccrodp** [comment]
>why deal breaker? It's just checks you are running inside a git project.

I wasn't sure, but sounded like it might be. However, your simple work around for the time being doesn't sound too cumbersome or bad practice, so it sounds perfect in the meantime. You never know, if I get more into it and upskill, that use case might be something I can look into, but it's early days yet.

Going to add that work around for now via Dockerfile and get back to this issue with the hope of closing it. Many thanks!

**Comment by mccrodp** [comment]
Hey @amitaibu. Managed to get over the git requirement on the built image, however we're back to the `client.end is not a function` error. Maybe we can discuss later today and I'll take a closer look at *shoov-webdrivercss/index.js* soon.

````
shoov@f46c54d9816a:~/visual-monitor$ PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha


  Visual monitor testing
    1) "before all" hook
Unhandled rejection TypeError: client.end is not a function
    at /home/shoov/visual-monitor/node_modules/shoov-webdrivercss/index.js:236:16
    at tryCatcher (/home/shoov/visual-monitor/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/shoov/visual-monitor/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/shoov/visual-monitor/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
````

**Comment by mccrodp** [comment]
Hey. I rebuilt this today locally after a break from it and when running it I did not encounter the error. It seemed to run the tests smoothly. The thing is I though, my Saucelabs account associated to the `.shoov.json` has expired, so I'm not sure if it falls back to Phantom.js in this case and that's why I didn't see the error.

I'm going to reactivate the Saucelabs account tomorrow and try again.

**Comment by mccrodp** [comment]
Not seeing this issue anymore, so closing for now. Thanks for help with it.
